apiVersion: apps/v1
kind: Deployment
metadata:
  name: grow-achievement-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: achievement
  template:
    metadata:
      labels:
        app: achievement
    spec:
      containers:
        - name: achievement
          image: yeonju7547/grow-achievement:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          envFrom:
            - secretRef:
                name: grow-achievement-secret
---
apiVersion: v1
kind: Service
metadata:
  name: achievement
spec:
  type: ClusterIP
  selector:
    app: achievement
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grow-achievement-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grow-achievement-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
