apiVersion: v1
kind: Secret
metadata:
  name: grow-achievement-secret
type: Opaque
stringData:
  SERVER_PORT: "3002"

  DB_HOST: "34.50.60.106"
  DB_PORT: "3306"
  DB_NAME: "achievement_db"
  DB_USER: "grow_user"
  DB_PASSWORD: "Grow1234!"

  RABBITMQ_HOST: "34.50.25.118"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
